//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class componentesxcomputadora
    {
        public int idComponentesXComputadora { get; set; }
        public int idComputadora { get; set; }
        public int idComponente { get; set; }
    
        public virtual componente componente { get; set; }
        public virtual computadora computadora { get; set; }
    }
}
