//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineapresupuesto
    {
        public int idLineaPresupuesto { get; set; }
        public int idPresupuesto { get; set; }
        public int idProducto { get; set; }
        public double PrecioUnit { get; set; }
        public int Cantidad { get; set; }
    
        public virtual presupuesto presupuesto { get; set; }
        public virtual producto producto { get; set; }
    }
}
