//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaElectronica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiendaelectronicaEntities : DbContext
    {
        public tiendaelectronicaEntities()
            : base("name=tiendaelectronicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caracteristica> caracteristica { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<compatibilidad> compatibilidad { get; set; }
        public virtual DbSet<componente> componente { get; set; }
        public virtual DbSet<componentesxcomputadora> componentesxcomputadora { get; set; }
        public virtual DbSet<computadora> computadora { get; set; }
        public virtual DbSet<lineapresupuesto> lineapresupuesto { get; set; }
        public virtual DbSet<presupuesto> presupuesto { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<tipocomponente> tipocomponente { get; set; }
        public virtual DbSet<tipocomputadora> tipocomputadora { get; set; }
        public virtual DbSet<tipoxproducto> tipoxproducto { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<tipodeusuario> tipodeusuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
