//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoxproducto
    {
        public int idTipoXProducto { get; set; }
        public int idTipoComputadora { get; set; }
        public int idProducto { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual tipocomputadora tipocomputadora { get; set; }
    }
}
