//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int idVenta { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public int IdPresupuesto { get; set; }
        public int FacturaNro { get; set; }
    
        public virtual presupuesto presupuesto { get; set; }
    }
}
